version: '3.8'

services:
  db:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    restart: always
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
  
  web:
    build: .
    restart: always
    depends_on:
      - db
    expose:
      - "5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=wsgi.py
      - DATABASE_URL=mysql+pymysql://username:password@db:3306/flask_db
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=username
      - DATABASE_PASSWORD=password
      - DATABASE_DB=flask_db
    networks:
      - backend
    command: gunicorn --bind 0.0.0.0:5000 -w 4 --timeout 90 wsgi:app

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - backend

networks:
  backend:

volumes:
  db_data:

