# Use the official Nginx image
FROM nginx:latest

# Copy custom Nginx configuration file to container
COPY nginx.conf /etc/nginx/nginx.conf

# Expose ports
EXPOSE 80
EXPOSE 443

# Start Nginx when container launches
CMD ["nginx", "-g", "daemon off;"]

