version: '3.8'
services:
  db:
    image: mariadb:10.5
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: flask_db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    image: blog_web:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    expose:
      - "5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=wsgi.py
      - DATABASE_URL=mysql+pymysql://username:password@db:3306/flask_db
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=username
      - DATABASE_PASSWORD=password
      - DATABASE_DB=flask_db
    networks:
      - backend
    command: sh -c " sleep 20 && sleep 10 && gunicorn --bind 0.0.0.0:5000 -w 4 --timeout 90 wsgi:app"
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    image: blog_nginx:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: any
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
    volumes:
      - /etc/letsencrypt/live/docker.aliahmad.sumamazaeem.com:/etc/letsencrypt/live/docker.aliahmad.sumamazaeem.com:ro
      - /etc/letsencrypt/archive/docker.aliahmad.sumamazaeem.com:/etc/letsencrypt/archive/docker.aliahmad.sumamazaeem.com:ro
        #  command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - web

networks:
  backend:
    driver: overlay

volumes:
  db_data:
